// Mocks generated by Mockito 5.4.6 from annotations
// in ponto_eletronico/test/mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:firebase_auth/firebase_auth.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i9;
import 'package:ponto_eletronico/domain/entities/time_record_entity.dart'
    as _i7;
import 'package:ponto_eletronico/domain/entities/user_entity.dart' as _i3;
import 'package:ponto_eletronico/domain/repositories/i_auth_repository.dart'
    as _i4;
import 'package:ponto_eletronico/domain/repositories/i_time_record_repository.dart'
    as _i6;
import 'package:ponto_eletronico/domain/repositories/i_user_repository.dart'
    as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeUserCredential_0 extends _i1.SmartFake
    implements _i2.UserCredential {
  _FakeUserCredential_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUserEntity_1 extends _i1.SmartFake implements _i3.UserEntity {
  _FakeUserEntity_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [IAuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIAuthRepository extends _i1.Mock implements _i4.IAuthRepository {
  MockIAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.UserCredential> login(String? email, String? password) =>
      (super.noSuchMethod(
            Invocation.method(#login, [email, password]),
            returnValue: _i5.Future<_i2.UserCredential>.value(
              _FakeUserCredential_0(
                this,
                Invocation.method(#login, [email, password]),
              ),
            ),
          )
          as _i5.Future<_i2.UserCredential>);

  @override
  _i5.Future<void> logout() =>
      (super.noSuchMethod(
            Invocation.method(#logout, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}

/// A class which mocks [ITimeRecordRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockITimeRecordRepository extends _i1.Mock
    implements _i6.ITimeRecordRepository {
  MockITimeRecordRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<void> registerEntry(_i7.TimeRecordEntity? record) =>
      (super.noSuchMethod(
            Invocation.method(#registerEntry, [record]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> registerExit(String? recordId, DateTime? exit) =>
      (super.noSuchMethod(
            Invocation.method(#registerExit, [recordId, exit]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<_i7.TimeRecordEntity?> getTodayRecord(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getTodayRecord, [userId]),
            returnValue: _i5.Future<_i7.TimeRecordEntity?>.value(),
          )
          as _i5.Future<_i7.TimeRecordEntity?>);

  @override
  _i5.Future<List<_i7.TimeRecordEntity>> getMonthlyRecords(
    String? userId, {
    required int? month,
    required int? year,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getMonthlyRecords,
              [userId],
              {#month: month, #year: year},
            ),
            returnValue: _i5.Future<List<_i7.TimeRecordEntity>>.value(
              <_i7.TimeRecordEntity>[],
            ),
          )
          as _i5.Future<List<_i7.TimeRecordEntity>>);

  @override
  _i5.Stream<List<_i7.TimeRecordEntity>> watchTodayRecords() =>
      (super.noSuchMethod(
            Invocation.method(#watchTodayRecords, []),
            returnValue: _i5.Stream<List<_i7.TimeRecordEntity>>.empty(),
          )
          as _i5.Stream<List<_i7.TimeRecordEntity>>);

  @override
  _i5.Stream<List<_i7.TimeRecordEntity>> watchMonthlyRecords({
    required int? month,
    required int? year,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#watchMonthlyRecords, [], {
              #month: month,
              #year: year,
            }),
            returnValue: _i5.Stream<List<_i7.TimeRecordEntity>>.empty(),
          )
          as _i5.Stream<List<_i7.TimeRecordEntity>>);

  @override
  _i5.Future<void> updateRecord(_i7.TimeRecordEntity? record) =>
      (super.noSuchMethod(
            Invocation.method(#updateRecord, [record]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}

/// A class which mocks [IUserRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIUserRepository extends _i1.Mock implements _i8.IUserRepository {
  MockIUserRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i3.UserEntity> getUser(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getUser, [userId]),
            returnValue: _i5.Future<_i3.UserEntity>.value(
              _FakeUserEntity_1(this, Invocation.method(#getUser, [userId])),
            ),
          )
          as _i5.Future<_i3.UserEntity>);

  @override
  _i5.Future<String> getRole(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getRole, [userId]),
            returnValue: _i5.Future<String>.value(
              _i9.dummyValue<String>(
                this,
                Invocation.method(#getRole, [userId]),
              ),
            ),
          )
          as _i5.Future<String>);

  @override
  _i5.Future<List<_i3.UserEntity>> getAllEmployees() =>
      (super.noSuchMethod(
            Invocation.method(#getAllEmployees, []),
            returnValue: _i5.Future<List<_i3.UserEntity>>.value(
              <_i3.UserEntity>[],
            ),
          )
          as _i5.Future<List<_i3.UserEntity>>);

  @override
  _i5.Future<void> deleteEmployee(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteEmployee, [userId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> createEmployee({
    required String? name,
    required String? email,
    required String? password,
    required String? role,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createEmployee, [], {
              #name: name,
              #email: email,
              #password: password,
              #role: role,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> updateUser(_i3.UserEntity? user) =>
      (super.noSuchMethod(
            Invocation.method(#updateUser, [user]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}
