// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANe4LFfEbBIuQ0AJ6eg3_--XpLH4Wa-NA',
    appId: '1:554374796089:web:ff123316cd469aa71b8ee8',
    messagingSenderId: '554374796089',
    projectId: 'ponto-eletronico-66dee',
    authDomain: 'ponto-eletronico-66dee.firebaseapp.com',
    storageBucket: 'ponto-eletronico-66dee.firebasestorage.app',
    measurementId: 'G-G121H1KW2Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsITZ6EdHnJNIkJOiKLQcL-u_7ktkxSlQ',
    appId: '1:554374796089:android:eedfe2e6eabb7b3f1b8ee8',
    messagingSenderId: '554374796089',
    projectId: 'ponto-eletronico-66dee',
    storageBucket: 'ponto-eletronico-66dee.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRB0rKU4OQGQpot4faidkNhcSfc6Jp1F0',
    appId: '1:554374796089:ios:8b54d35c9f00bb581b8ee8',
    messagingSenderId: '554374796089',
    projectId: 'ponto-eletronico-66dee',
    storageBucket: 'ponto-eletronico-66dee.firebasestorage.app',
    iosBundleId: 'com.example.pontoEletronico',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRB0rKU4OQGQpot4faidkNhcSfc6Jp1F0',
    appId: '1:554374796089:ios:8b54d35c9f00bb581b8ee8',
    messagingSenderId: '554374796089',
    projectId: 'ponto-eletronico-66dee',
    storageBucket: 'ponto-eletronico-66dee.firebasestorage.app',
    iosBundleId: 'com.example.pontoEletronico',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyANe4LFfEbBIuQ0AJ6eg3_--XpLH4Wa-NA',
    appId: '1:554374796089:web:c1cb68f5c0218b061b8ee8',
    messagingSenderId: '554374796089',
    projectId: 'ponto-eletronico-66dee',
    authDomain: 'ponto-eletronico-66dee.firebaseapp.com',
    storageBucket: 'ponto-eletronico-66dee.firebasestorage.app',
    measurementId: 'G-L2S20QHNQ0',
  );
}
